version: 2.1
jobs:
  build-user-service:
    docker:
    - image: circleci/node:12.18.2
    steps:
      - checkout
      - run: 
          name: Install
          command: |
            pwd
            ls
            npm install
      - run: 
          working_directory: ~/project/Demos/6Week/user-service
          name: Test
          command: |
            npm test
      - run: 
          working_directory: ~/project/Demos/6Week/user-service
          name: Build
          command: |
            npm run build
workflows:
    build-and-test:
      jobs:
        - build-user-service
