version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-user-service:
    docker:
    - image: circleci/node:12.18.3
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                working_directory: ~/6Week/user-service
                name: Install
                command: |
                  npm install
            - run: 
                working_directory: ~/6Week/user-service
                name: Test
                command: |
                  npm test
            - run: 
                working_directory: ~/6Week/user-service
                name: Build
                command: |
                  npm run build
workflows:
    build-and-test:
      jobs:
        - build-user-service
